spring:
  kafka:
    consumer:
#     otherwise: No group.id found in consumer config, container properties, or @KafkaListener annotation; a group.id is required when group management is used.
      group-id: my-group-id
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#     otherwise: The class 'com.example.BankTransfer' is not in the trusted packages: [java.util, java.lang].
      properties:
        spring.json.trusted.packages: com.example
